language: android
jdk: oraclejdk8
sudo: true
os:
  - linux
addons:
  apt_packages:
    - pandoc
before_install:
  - mkdir -p $ANDROID_HOME/licenses
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "ndk;18.1.5063045"
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "cmake;3.10.2.4988404"
before_script:
  - export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
  - export ANDROID_NDK_HOME=$ANDROID_NDK_ROOT
script:
  - ./gradlew clean check --profile
  - pandoc `ls -1rt build/reports/profile/profile-*.html | tail -n1` -t plain
  - ./gradlew build